      SUBROUTINE CALCULATOR(MEASURE, PAGE, CH)
        CHARACTER*80 MEASURE
        CHARACTER*2 CH
        CHARACTER*1 PAGE
        
        IF(PAGE .EQ. '1') THEN
          IF(CH .EQ. '1') CALL CALC_MATCHBOX(MEASURE)
          IF(CH .EQ. '2') CALL CALC_TETRAHEDRON(MEASURE)
          IF(CH .EQ. '3') CALL CALC_OBELISK(MEASURE)
          IF(CH .EQ. '4') CALL CALC_WEDGE(MEASURE)
          IF(CH .EQ. '5') CALL CALC_STRAIGHT_CYLINDER(MEASURE)
          IF(CH .EQ. '6') CALL CALC_TRUNCATED_CYLINDER(MEASURE)
        ELSE IF(PAGE .EQ. '2') THEN
          IF(CH .EQ. '2') CALL CALC_CYLINDER_SEGMENT(MEASURE)
          IF(CH .EQ. '3') CALL CALC_CYLINDRICAL_TUBE(MEASURE)
          IF(CH .EQ. '4') CALL CALC_STRAIGHT_CONE(MEASURE)
          IF(CH .EQ. '5') CALL CALC_TRUNCATED_CONE(MEASURE)
          IF(CH .EQ. '6') CALL CALC_SPHERE(MEASURE)
        ELSE IF(PAGE .EQ. '3') THEN
          IF(CH .EQ. '2') CALL CALC_SPHERE_SECTOR(MEASURE)
          IF(CH .EQ. '3') CALL CALC_SPHERE_SEGMENT(MEASURE)
          IF(CH .EQ. '4') CALL CALC_SPHERE_LAYER(MEASURE)
          IF(CH .EQ. '5') CALL CALC_TORUS(MEASURE)
          IF(CH .EQ. '6') CALL CALC_SPHERE_BARREL(MEASURE)
          IF(CH .EQ. '7') CALL CALC_PARABOLIC_BARREL(MEASURE)
        END IF
      END
